#!/bin/bash

while test $# -gt 0; do
case "$1" in
    -h|--help)
    echo "cpenv - attempt to capture frames"
    echo " "
    echo "cpenv [options] application [arguments]"
    echo " "
    echo "options:"
    echo "-h, --help                show brief help"
    echo "-l, --lang=LANGUAGE       specify an action to use"
    #echo "-o, --output-dir=DIR      specify a directory to store output in"
    exit 0
    ;;
    -l)
    shift
    if test $# -gt 0; then
        export LANG=$1
        #export PROCESS=`echo $1 | sed -e 's/^[^=]*=//g'`
    else
        echo "no process specified"
        exit 1
    fi
    shift
    ;;
    --action*)
    export LANG=`echo $1 | sed -e 's/^[^=]*=//g'`
    shift
    ;;

    -p)
    shift
    if test $# -gt 0; then
        export PROBLEM_NAME=$1
        #export PROCESS=`echo $1 | sed -e 's/^[^=]*=//g'`
    else
        echo "Using default problem name: Solution"
        exit 1
    fi
    shift
    ;;

    # -o)
    # shift
    # if test $# -gt 0; then
    #     export OUTPUT=$1
    # else
    #     echo "no output dir specified"
    #     exit 1
    # fi
    # shift
    # ;;
    # --output-dir*)
    # export OUTPUT=`echo $1 | sed -e 's/^[^=]*=//g'`
    # shift
    # ;;
    # *)
    # break
    # ;;
esac
done

function make_io_files {
    touch input.txt
    touch output.txt
}

function add_meta_info {

    sed -i "1s/^/\/**\n* Author: Vedant Wankhade\n* Date: $(date +%m-%d-%Y)\n*\/\n\n/" ./${PROBLEM_NAME}.$1
}

function create_cpp_env {

    echo "Creating C++ CP env..."
    cp ~/.cpenv/cpp-template ./${PROBLEM_NAME}.cpp
    # sed -i "s/Solution/$PROBLEM_NAME/" ./${PROBLEM_NAME}.cpp 

    add_meta_info "cpp" 
    echo "Creating i/o files..."
    make_io_files
    echo "Done"
}

function create_java_env {

    echo "Creating Java CP env..."
    cp ~/.cpenv/java-template ./${PROBLEM_NAME}.java
    sed -i "s/Solution/$PROBLEM_NAME/" ./${PROBLEM_NAME}.java 

    add_meta_info "java"
    echo "Creating i/o files..."
    make_io_files
    echo "Done"
}

if [ "$LANG" == "cpp" ]; then
    
    create_cpp_env

elif [ "$LANG" == "java" ]; then

    create_java_env

else echo Wrong LANG input

fi
